# Generated by Django 4.0.5 on 2022-06-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0002_message_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conversations',
            new_name='conversations_list',
        ),
    ]
