# Generated by Django 4.0.5 on 2022-06-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_api', '0003_rename_conversations_user_conversations_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conversations_list',
            new_name='conversations',
        ),
    ]
